<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>..\VaultCrypt.Core\Properties\VaultCryptLogo.ico</ApplicationIcon>
        <AssemblyName>VaultCrypt.WPF</AssemblyName>
        <RootNamespace>VaultCrypt.WPF</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\VaultCrypt.Core\VaultCrypt.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\VaultCrypt.Core\Properties\VaultCryptLogo.ico" />
    </ItemGroup>
</Project>